//! Extension Register Definitions
//!
//! ESP32-specific extension registers for clock, GPIO, and power management.

use super::{EXT_BASE, read_reg, reg_ro, reg_rw, write_reg};

// =============================================================================
// Register Offsets
// =============================================================================

/// Extended Configuration Register offset
pub const EX_OSCCLK_CONF_OFFSET: usize = 0x00;
/// Clock Enable/Disable Register offset
pub const EX_CLK_CTRL_OFFSET: usize = 0x04;
/// PHY Clock Configuration Register offset
pub const EX_PHYINF_CONF_OFFSET: usize = 0x08;
/// PD Select Register offset
pub const EX_PD_SEL_OFFSET: usize = 0x0C;
/// RAM Power Down Register offset
pub const EX_RAM_PD_OFFSET: usize = 0x10;
/// Date Register offset
pub const EX_DATE_OFFSET: usize = 0xFC;

// =============================================================================
// Extended Oscillator Configuration (EX_OSCCLK_CONF) Bits
// =============================================================================

/// Enable external oscillator reference clock
pub const EX_OSCCLK_OSC_EN: u32 = 1 << 0;
/// External oscillator clock enable for RMII
pub const EX_OSCCLK_CLK_SEL: u32 = 1 << 1;
/// MII/RMII clock division factor shift
pub const EX_OSCCLK_DIV_SHIFT: u32 = 2;
/// MII/RMII clock division factor mask (8 bits)
pub const EX_OSCCLK_DIV_MASK: u32 = 0xFF << 2;

// =============================================================================
// Clock Control Register (EX_CLK_CTRL) Bits
// =============================================================================

/// Enable RMII external clock
pub const EX_CLK_MII_CLK_RX_EN: u32 = 1 << 0;
/// Enable MII clock for RX
pub const EX_CLK_MII_CLK_TX_EN: u32 = 1 << 1;
/// Enable clock generation
pub const EX_CLK_EN: u32 = 1 << 5;

// =============================================================================
// PHY Interface Configuration (EX_PHYINF_CONF) Bits
// =============================================================================

/// PHY interface select: 0 = MII, 1 = RMII
pub const EX_PHYINF_RMII_EN: u32 = 1 << 0;
/// RMII external TX clock enable (if using external clock)
pub const EX_PHYINF_RMII_EXT_TX_CLK_EN: u32 = 1 << 1;
/// RMII external RX clock enable
pub const EX_PHYINF_RMII_EXT_RX_CLK_EN: u32 = 1 << 2;
/// RMII clock source select: 0 = external, 1 = internal
pub const EX_PHYINF_RMII_CLK_SEL: u32 = 1 << 3;
/// Clock inversion
pub const EX_PHYINF_CLK_INV: u32 = 1 << 4;
/// Disk loop back
pub const EX_PHYINF_DISK_LB: u32 = 1 << 5;
/// Enable RMII REF clock output (for GPIO16/17)
pub const EX_PHYINF_RMII_REF_CLK_OUT_EN: u32 = 1 << 6;
/// RMII loopback enable
pub const EX_PHYINF_RMII_LB: u32 = 1 << 7;

// =============================================================================
// Power Down Select (EX_PD_SEL) Bits
// =============================================================================

/// Power down select for RAM
pub const EX_PD_SEL_RAM_PD: u32 = 1 << 0;

// =============================================================================
// Extension Register Access Functions
// =============================================================================

/// Extension Register block for type-safe access
pub struct ExtRegs;

impl ExtRegs {
    /// Get the base address
    #[inline(always)]
    pub const fn base() -> usize {
        EXT_BASE
    }

    // -------------------------------------------------------------------------
    // Register accessors (generated by macros)
    // -------------------------------------------------------------------------

    reg_rw!(
        osc_clk_conf,
        set_osc_clk_conf,
        EXT_BASE,
        EX_OSCCLK_CONF_OFFSET,
        "Oscillator Clock Configuration"
    );
    reg_rw!(
        clk_ctrl,
        set_clk_ctrl,
        EXT_BASE,
        EX_CLK_CTRL_OFFSET,
        "Clock Control register"
    );
    reg_rw!(
        phy_inf_conf,
        set_phy_inf_conf,
        EXT_BASE,
        EX_PHYINF_CONF_OFFSET,
        "PHY Interface Configuration"
    );
    reg_rw!(
        pd_sel,
        set_pd_sel,
        EXT_BASE,
        EX_PD_SEL_OFFSET,
        "Power Down Select register"
    );
    reg_rw!(
        ram_pd,
        set_ram_pd,
        EXT_BASE,
        EX_RAM_PD_OFFSET,
        "RAM Power Down register"
    );
    reg_ro!(
        date,
        EXT_BASE,
        EX_DATE_OFFSET,
        "Date register (version info)"
    );

    // -------------------------------------------------------------------------
    // Clock control helpers
    // -------------------------------------------------------------------------

    /// Enable EMAC clocks
    #[inline(always)]
    pub fn enable_clocks() {
        unsafe {
            let ctrl = read_reg(EXT_BASE + EX_CLK_CTRL_OFFSET);
            write_reg(
                EXT_BASE + EX_CLK_CTRL_OFFSET,
                ctrl | EX_CLK_MII_CLK_RX_EN | EX_CLK_MII_CLK_TX_EN | EX_CLK_EN,
            );
        }
    }

    /// Disable EMAC clocks
    #[inline(always)]
    pub fn disable_clocks() {
        unsafe {
            let ctrl = read_reg(EXT_BASE + EX_CLK_CTRL_OFFSET);
            write_reg(
                EXT_BASE + EX_CLK_CTRL_OFFSET,
                ctrl & !(EX_CLK_MII_CLK_RX_EN | EX_CLK_MII_CLK_TX_EN | EX_CLK_EN),
            );
        }
    }

    // -------------------------------------------------------------------------
    // PHY interface helpers
    // -------------------------------------------------------------------------

    /// Configure for RMII mode
    #[inline(always)]
    pub fn set_rmii_mode() {
        unsafe {
            let conf = read_reg(EXT_BASE + EX_PHYINF_CONF_OFFSET);
            write_reg(EXT_BASE + EX_PHYINF_CONF_OFFSET, conf | EX_PHYINF_RMII_EN);
        }
    }

    /// Configure for MII mode
    #[inline(always)]
    pub fn set_mii_mode() {
        unsafe {
            let conf = read_reg(EXT_BASE + EX_PHYINF_CONF_OFFSET);
            write_reg(EXT_BASE + EX_PHYINF_CONF_OFFSET, conf & !EX_PHYINF_RMII_EN);
        }
    }

    /// Set RMII clock to external source
    #[inline(always)]
    pub fn set_rmii_clock_external() {
        unsafe {
            let conf = read_reg(EXT_BASE + EX_PHYINF_CONF_OFFSET);
            write_reg(
                EXT_BASE + EX_PHYINF_CONF_OFFSET,
                (conf | EX_PHYINF_RMII_EXT_RX_CLK_EN) & !EX_PHYINF_RMII_CLK_SEL,
            );
        }
    }

    /// Set RMII clock to internal source with output
    #[inline(always)]
    pub fn set_rmii_clock_internal() {
        unsafe {
            let conf = read_reg(EXT_BASE + EX_PHYINF_CONF_OFFSET);
            write_reg(
                EXT_BASE + EX_PHYINF_CONF_OFFSET,
                conf | EX_PHYINF_RMII_CLK_SEL | EX_PHYINF_RMII_REF_CLK_OUT_EN,
            );
        }
    }

    // -------------------------------------------------------------------------
    // Power management helpers
    // -------------------------------------------------------------------------

    /// Power up EMAC RAM
    #[inline(always)]
    pub fn power_up_ram() {
        Self::set_ram_pd(0);
    }

    /// Power down EMAC RAM
    #[inline(always)]
    pub fn power_down_ram() {
        Self::set_ram_pd(0xFFFF_FFFF);
    }
}
